spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
#    hibernate:
#      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: gks777777@gmail.com
    password: lumsqwufypviqxvp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 300000  # 5 * 60 * 1000 == 5분